baseurl = "https://gamingcreed.netlify.app"
languageCode = "en"
defaultContentLanguage = "en"
title = "Gamers Kreed"
theme = "hugo-theme-dream"

#copyright = "© 2020 Gamers Kreed"
#copyright = "2020 Gamers Kreed"

googleAnalytics = "UA-162830290-2"

# disqusShortname = ""

enableRobotsTXT = true

# [taxonomies]
# author = "authors"
# tag = "tags"
# category = "categories"
# serie = "series"

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "Gamers Kreed"
  description = "Gamers gather here to accomplish a Common goal. The Goal is to enforce our will upon any game that presents itself before us."
  #avatar = "/img/avatar.jpg"
  avatar = "/img/GamersKreed-Logo-1.gif"
  motto = "Ready Player One?"

 # Social Settings:
  youtube = "channel/UCgjpweeQVLjZ3qmaWGSyp3w"
  discord = "channels/714301822646353940"
  # github = "https:github.com/gamerskreed"
  twitter = "gamerskreed"
  email = "Gamers.Kreed@gmail.com"
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2020

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
